name: Automatic Build
on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ['manu-homelab']
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup Java
            uses: actions/setup-java@v1
            with:
              java-version: '17'
          - name: Run chmod to make gradlew executable
            run: chmod +x ./gradlew
          - name: Build
            uses: gradle/gradle-build-action@v2
            with:
              arguments: build
          - name: Upload File to our api
            id: upload
            uses: modcraftmc/upload-artifact-action@1.4
            with:
             url: https:/api.modcraftmc.fr/v1/updater/upload
             bearerAuthorization: ${{ secrets.API_KEY }}
             fileForms: '{"launcher":"build/libs/launcher.jar"}'
